# Generated by Django 2.1.2 on 2018-10-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=32),
        ),
    ]
